[default]
extend-ignore-re = ['(?m)^\s*(//|#).*\r?\n?$']
[default.extend-words]
END-FF = "END-FF"
Monopolis = "Monopolis"
moreso = "moreso"
Whaat = "Whaat"
Wha = "Wha"
KNW = "KNW"
Vor = "Vor"
Gae = "Gae"
goin = "goin"
Goin = "Goin"
somethin = "somethin"
Somethin = "Somethin"
takin = "takin"
lookin = "lookin"
Lookin = "Lookin"
makin = "makin"
givin = "givin"
doin = "doin"
runnin = "runnin"
usin = "usin"
excitin = "excitin"
completin = "completin"
challengin = "challengin"
participatin = "participatin"
deceivin = "deceivin"
promisin = "promisin"
preparin = "preparin"
amazin = "amazin"
Everythin = "Everythin"
everythin = "everythin"
appen = "appen"
adn = "adn"
Dum = "Dum"
dum = "dum"
Amazin = "Amazin"
