[default]
extend-ignore-re = ['(?m)^\s*(//|#).*\r?\n?$']

[default.extend-words]
END-FF = "END-FF"
Monopolis = "Monopolis"
moreso = "moreso"
Whaat = "Whaat"
Wha = "Wha"
KNW = "KNW"
Vor = "Vor"
Gae = "Gae"

[files]
extend-exclude = [
  "**/source/GL6_SCEN.DAT/00000034.SCEN*",
  "**/source/GL6_SCEN.DAT/00000079.SCEN*",
  "**/source/GL6_SCEN.DAT/00000086.SCEN*"
]
