name: Build xDelta Patch
on: workflow_dispatch

jobs:
  BuildPatch:
    name: Build xDelta Patch for the Growlanser 6 English Translation
    runs-on: windows-2022
    steps:
      - name: 01. Copy repository
        uses: actions/checkout@v4
        with:
          sparse-checkout: | # Only copy specific folders to the container
            .github
            build
            source
            tools
      - name: Test
        shell: powershell
        env:
          TEST: ${{ secrets.TEST }}
        run: |
          Read-S3Object $Env:TEST -File "$Env:GITHUB_WORKSPACE\build\07-translates_files\DUMMY.DAT"
          ls "$Env:GITHUB_WORKSPACE\build\07-translates_files"
      # - name: 02. Prepare files
      #   shell: powershell
      #   env:
      #     DUMMY: ${{ secrets.DUMMY }}
      #     BTL: ${{ secrets.BTL }}
      #     CHAR: ${{ secrets.CHAR }}
      #     FACE: ${{ secrets.FACE }}
      #     FILE: ${{ secrets.FILE }}
      #     MAP: ${{ secrets.MAP }}
      #     MOV: ${{ secrets.MOV }}
      #     SCEN: ${{ secrets.SCEN }}
      #     SND: ${{ secrets.SND }}
      #     VOI: ${{ secrets.VOI }}
      #     IOPRP300: ${{ secrets.IOPRP300 }}
      #     SLPM: ${{ secrets.SLPM }}
      #     SYSTEM: ${{ secrets.SYSTEM }}
      #     GL6: ${{ secrets.GL6 }}
      #   run: |
      #     # Download files
      #     echo "DUMMY to 07"
      #     Invoke-WebRequest -Uri "$Env:DUMMY" -OutFile "$Env:GITHUB_WORKSPACE\build\07-translates_files\DUMMY.DAT"

      #     echo "BTL to 07"
      #     Invoke-WebRequest -Uri "$Env:BTL" -OutFile "$Env:GITHUB_WORKSPACE\build\07-translates_files\GL6_BTL.DAT"

      #     echo "CHAR to 07"
      #     Invoke-WebRequest -Uri "$Env:CHAR" -OutFile "$Env:GITHUB_WORKSPACE\build\07-translates_files\GL6_CHAR.DAT"

      #     echo "FACE to 06"
      #     Invoke-WebRequest -Uri "$Env:FACE" -OutFile "$Env:GITHUB_WORKSPACE\build\06-original_files\GL6_FACE.DAT"

      #     echo "FILE to 06"
      #     Invoke-WebRequest -Uri "$Env:FILE" -OutFile "$Env:GITHUB_WORKSPACE\build\06-original_files\GL6_FILE.DAT"

      #     echo "MAP to 07"
      #     Invoke-WebRequest -Uri "$Env:MAP" -OutFile "$Env:GITHUB_WORKSPACE\build\07-translates_files\GL6_MAP.DAT"

      #     echo "MOV to 07"
      #     Invoke-WebRequest -Uri "$Env:MOV" -OutFile "$Env:GITHUB_WORKSPACE\build\07-translates_files\GL6_MOV.DAT"

      #     echo "SCEN to 06"
      #     Invoke-WebRequest -Uri "$Env:SCEN" -OutFile "$Env:GITHUB_WORKSPACE\build\06-original_files\GL6_SCEN.DAT"

      #     echo "SND to 07"
      #     Invoke-WebRequest -Uri "$Env:SND" -OutFile "$Env:GITHUB_WORKSPACE\build\07-translates_files\GL6_SND.DAT"

      #     echo "VOI to 07"
      #     Invoke-WebRequest -Uri "$Env:VOI" -OutFile "$Env:GITHUB_WORKSPACE\build\07-translates_files\GL6_VOI.DAT"

      #     echo "IOPRP300 to 07"
      #     Invoke-WebRequest -Uri "$Env:IOPRP300" -OutFile "$Env:GITHUB_WORKSPACE\build\07-translates_files\IOPRP300.IMG"

      #     echo "SLPM to 06"
      #     Invoke-WebRequest -Uri "$Env:SLPM" -OutFile "$Env:GITHUB_WORKSPACE\build\06-original_files\SLPM_667.16"

      #     echo "SYSTEM to 07"
      #     Invoke-WebRequest -Uri "$Env:SYSTEM" -OutFile "$Env:GITHUB_WORKSPACE\build\07-translates_files\SYSTEM.CNF"

      #     echo "GL6 to 06"
      #     Invoke-WebRequest -Uri "$Env:GL6" -OutFile "$Env:GITHUB_WORKSPACE\build\06-original_files\Growlanser 6 Precarious World.iso"
      # - name: 03. Setup the build enviromnent
      #   shell: powershell
      #   run: |
      #     echo "Create the 05-Build directory"
      #     mkdir "$Env:GITHUB_WORKSPACE\build\05-build" -Force

      #     echo "Create the 06-Original files folders for the .DAT files"
      #     mkdir "$Env:GITHUB_WORKSPACE\build\06-original_files\GL6_FACE DAT" -Force
      #     mkdir "$Env:GITHUB_WORKSPACE\build\06-original_files\GL6_FILE DAT" -Force
      #     mkdir "$Env:GITHUB_WORKSPACE\build\06-original_files\GL6_SCEN DAT" -Force

      #     echo "Copy growlanser.bms, delete later"
      #     cp "$Env:GITHUB_WORKSPACE\tools\GL5 and 6 quickBMS scripts\growlanser.bms" "$Env:GITHUB_WORKSPACE\build\02-quickbms\growlanser.bms"

      #     echo "Start quickBMS to dump the .DAT files contents to the original files folder"
      #     cmd.exe /C "$Env:GITHUB_WORKSPACE\build\02-quickbms\quickbms.exe" -w "$Env:GITHUB_WORKSPACE\tools\GL5 and 6 quickBMS scripts\growlanser.bms" "$Env:GITHUB_WORKSPACE\build\06-original_files\GL6_FACE.DAT" "$Env:GITHUB_WORKSPACE\build\06-original_files\GL6_FACE DAT"
      #     cmd.exe /C "$Env:GITHUB_WORKSPACE\build\02-quickbms\quickbms.exe" -w "$Env:GITHUB_WORKSPACE\tools\GL5 and 6 quickBMS scripts\growlanser.bms" "$Env:GITHUB_WORKSPACE\build\06-original_files\GL6_FILE.DAT" "$Env:GITHUB_WORKSPACE\build\06-original_files\GL6_FILE DAT"
      #     cmd.exe /C "$Env:GITHUB_WORKSPACE\build\02-quickbms\quickbms.exe" -w "$Env:GITHUB_WORKSPACE\tools\GL5 and 6 quickBMS scripts\growlanser.bms" "$Env:GITHUB_WORKSPACE\build\06-original_files\GL6_SCEN.DAT" "$Env:GITHUB_WORKSPACE\build\06-original_files\GL6_SCEN DAT"

      #     echo "Unpack the *.FACE files"
      #     cmd.exe /C "$Env:GITHUB_WORKSPACE\build\02-quickbms\quickbms.exe" -w -d -F "*.FACE" "$Env:GITHUB_WORKSPACE\tools\GL5 and 6 quickBMS scripts\growlanser.bms" "$Env:GITHUB_WORKSPACE\build\06-original_files\GL6_FACE DAT" "$Env:GITHUB_WORKSPACE\build\06-original_files\GL6_FACE DAT"
      # - name: 04. Patch ELF
      #   shell: powershell
      #   run: |
      #     echo "Copy the repository files + ELF to the armips folder"
      #     cp "$Env:GITHUB_WORKSPACE\source\SLPM_667.16\SLPM_667.16_translation.asm" "$Env:GITHUB_WORKSPACE\build\01-armips\SLPM_667.16_translation.asm"
      #     cp "$Env:GITHUB_WORKSPACE\source\SLPM_667.16\SLPM_667.16_VWF.asm" "$Env:GITHUB_WORKSPACE\build\01-armips\SLPM_667.16_VWF.asm"
      #     cp "$Env:GITHUB_WORKSPACE\build\06-original_files\SLPM_667.16" "$Env:GITHUB_WORKSPACE\build\01-armips\SLPM_667.16"
      #     cp "$Env:GITHUB_WORKSPACE\tools\GL5 and 6 abcde scripts\abcde.tbl" "$Env:GITHUB_WORKSPACE\build\01-armips\abcde.tbl"

      #     echo "Switch to the armips folder and start the armips script"
      #     cd "$Env:GITHUB_WORKSPACE\build\01-armips\"
      #     cmd.exe /C "$Env:GITHUB_WORKSPACE\build\01-armips\armips.exe SLPM_667.16_translation.asm
      #     cmd.exe /C "$Env:GITHUB_WORKSPACE\build\01-armips\armips.exe SLPM_667.16_VWF.asm

      #     echo "Move patched ELF"
      #     cp "$Env:GITHUB_WORKSPACE\build\01-armips\SLPM_667.16" "$Env:GITHUB_WORKSPACE\build\07-translates_files\SLPM_667.16"
      # - name: 05. Translate files
      #   shell: powershell
      #   run: |
      #     echo "cd to the build folder"; cd "$Env:GITHUB_WORKSPACE\build"
      #     echo "execute build.bat"; cmd.exe -/c ".\build.bat"
      # - name: 06. Create patched version
      #   shell: powershell
      #   run: |
      #     echo "build"; python "$Env:GITHUB_WORKSPACE\build\04-isotool\isotool.py" --mode insert --iso "$Env:GITHUB_WORKSPACE\build\06-original_files\Growlanser 6 Precarious World.iso" --filelist "$Env:GITHUB_WORKSPACE\build\06-original_files\game_filelist.txt" --files "$Env:GITHUB_WORKSPACE\build\07-translates_files" --output "$Env:GITHUB_WORKSPACE\build\Growlanser 6 Precarious World English.iso" --with-padding
      # - name: 07. Create xDelta patch
      #   shell: powershell
      #   run: |
      #     echo "Create xDelta Patch"
      #     cmd.exe /C "$Env:GITHUB_WORKSPACE\build\03-xdelta\xdelta-3.1.0-x86_64.exe" -e -9 -S djw -vfs "$Env:GITHUB_WORKSPACE\build\06-original_files\Growlanser 6 Precarious World.iso" "$Env:GITHUB_WORKSPACE\build\Growlanser 6 Precarious World English.iso" "$Env:GITHUB_WORKSPACE\build\08-xDeltaPatch\vcdiff\Growlanser 6 Precarious World.iso.vcdiff"
          
      #     echo "remove vcdiff\file"
      #     rm "$Env:GITHUB_WORKSPACE\build\08-xDeltaPatch\vcdiff\file"
      # - name: 08. Publish patch
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: BuildBot-Growlanser_6_English_xDelta_Patch
      #     path: ${{ github.workspace }}\build\08-xDeltaPatch