name: Build xDelta Patch
on: workflow_dispatch

jobs:
  BuildPatch:
    name: Build xDelta Patch for the Growlanser 6 English Translation
    runs-on: windows-2022
    steps:
      - name: 01. Copy repository
        uses: actions/checkout@v4
        with:
          sparse-checkout: | # Only copy specific folders to the container
            .github
            build
            source
            tools

      - name: 02. Prepare files
        shell: powershell
        env:
          TEST: ${{ secrets.TEST }}
          TEST2: ${{ secrets.TEST2 }}
        run: |
          choco install megatools --yes
          # Download files
          megatools get -u "$Env:TEST" -p "$Env:TEST2" --path "$Env:GITHUB_WORKSPACE\build\07-translates_files\DUMMY.DAT" --no-progress /Root/00
          megatools get -u "$Env:TEST" -p "$Env:TEST2" --path "$Env:GITHUB_WORKSPACE\build\07-translates_files\GL6_BTL.DAT" --no-progress /Root/01
          megatools get -u "$Env:TEST" -p "$Env:TEST2" --path "$Env:GITHUB_WORKSPACE\build\07-translates_files\GL6_CHAR.DAT" --no-progress /Root/02
          megatools get -u "$Env:TEST" -p "$Env:TEST2" --path "$Env:GITHUB_WORKSPACE\build\06-original_files\GL6_FACE.DAT" --no-progress /Root/03
          megatools get -u "$Env:TEST" -p "$Env:TEST2" --path "$Env:GITHUB_WORKSPACE\build\06-original_files\GL6_FILE.DAT" --no-progress /Root/04
          megatools get -u "$Env:TEST" -p "$Env:TEST2" --path "$Env:GITHUB_WORKSPACE\build\07-translates_files\GL6_MAP.DAT" --no-progress /Root/05
          megatools get -u "$Env:TEST" -p "$Env:TEST2" --path "$Env:GITHUB_WORKSPACE\build\07-translates_files\GL6_MOV.DAT" --no-progress /Root/06
          megatools get -u "$Env:TEST" -p "$Env:TEST2" --path "$Env:GITHUB_WORKSPACE\build\06-original_files\GL6_SCEN.DAT" --no-progress /Root/07
          megatools get -u "$Env:TEST" -p "$Env:TEST2" --path "$Env:GITHUB_WORKSPACE\build\07-translates_files\GL6_SND.DAT" --no-progress /Root/08
          megatools get -u "$Env:TEST" -p "$Env:TEST2" --path "$Env:GITHUB_WORKSPACE\build\07-translates_files\GL6_VOI.DAT" --no-progress /Root/09
          megatools get -u "$Env:TEST" -p "$Env:TEST2" --path "$Env:GITHUB_WORKSPACE\build\07-translates_files\IOPRP300.IMG" --no-progress /Root/10
          megatools get -u "$Env:TEST" -p "$Env:TEST2" --path "$Env:GITHUB_WORKSPACE\build\06-original_files\SLPM_667.16" --no-progress /Root/11
          megatools get -u "$Env:TEST" -p "$Env:TEST2" --path "$Env:GITHUB_WORKSPACE\build\07-translates_files\SYSTEM.CNF" --no-progress /Root/12
          megatools get -u "$Env:TEST" -p "$Env:TEST2" --path "$Env:GITHUB_WORKSPACE\build\06-original_files\Growlanser 6 Precarious World.iso" --no-progress /Root/13

      - name: 03. Setup the build enviromnent
        shell: powershell
        run: |
          echo "[i] Create the 05-Build directory"
          New-Item -ItemType Directory -Force -Verbose -Path "$Env:GITHUB_WORKSPACE\build\05-build"

          echo "[i] Create the 06-Original files folders for the .DAT files"
          New-Item -ItemType Directory -Force -Verbose -Path "$Env:GITHUB_WORKSPACE\build\06-original_files\GL6_FACE DAT"  
          New-Item -ItemType Directory -Force -Verbose -Path "$Env:GITHUB_WORKSPACE\build\06-original_files\GL6_FILE DAT"
          New-Item -ItemType Directory -Force -Verbose -Path "$Env:GITHUB_WORKSPACE\build\06-original_files\GL6_SCEN DAT"

          echo "[i] Copy growlanser.bms, delete later"
          cp "$Env:GITHUB_WORKSPACE\tools\GL5 and 6 quickBMS scripts\growlanser.bms" "$Env:GITHUB_WORKSPACE\build\02-quickbms\growlanser.bms"

          echo "[i] Start quickBMS to dump the .DAT files contents to the original files folder"
          cmd.exe /C "$Env:GITHUB_WORKSPACE\build\02-quickbms\quickbms.exe" -w "$Env:GITHUB_WORKSPACE\tools\GL5 and 6 quickBMS scripts\growlanser.bms" "$Env:GITHUB_WORKSPACE\build\06-original_files\GL6_FACE.DAT" "$Env:GITHUB_WORKSPACE\build\06-original_files\GL6_FACE DAT"
          cmd.exe /C "$Env:GITHUB_WORKSPACE\build\02-quickbms\quickbms.exe" -w "$Env:GITHUB_WORKSPACE\tools\GL5 and 6 quickBMS scripts\growlanser.bms" "$Env:GITHUB_WORKSPACE\build\06-original_files\GL6_FILE.DAT" "$Env:GITHUB_WORKSPACE\build\06-original_files\GL6_FILE DAT"
          cmd.exe /C "$Env:GITHUB_WORKSPACE\build\02-quickbms\quickbms.exe" -w "$Env:GITHUB_WORKSPACE\tools\GL5 and 6 quickBMS scripts\growlanser.bms" "$Env:GITHUB_WORKSPACE\build\06-original_files\GL6_SCEN.DAT" "$Env:GITHUB_WORKSPACE\build\06-original_files\GL6_SCEN DAT"

          echo "[i] Unpack the *.FACE files"
          cmd.exe /C "$Env:GITHUB_WORKSPACE\build\02-quickbms\quickbms.exe" -w -d -F "*.FACE" "$Env:GITHUB_WORKSPACE\tools\GL5 and 6 quickBMS scripts\growlanser.bms" "$Env:GITHUB_WORKSPACE\build\06-original_files\GL6_FACE DAT" "$Env:GITHUB_WORKSPACE\build\06-original_files\GL6_FACE DAT"

      - name: 04. Patch ELF
        shell: powershell
        run: |
          echo "[i] Copy the repository files + ELF to the armips folder"
          Copy-Item -Verbose -Path "$Env:GITHUB_WORKSPACE\source\SLPM_667.16\SLPM_667.16_translation.asm" -Destination "$Env:GITHUB_WORKSPACE\build\01-armips\SLPM_667.16_translation.asm"
          Copy-Item -Verbose -Path "$Env:GITHUB_WORKSPACE\source\SLPM_667.16\SLPM_667.16_VWF.asm" -Destination "$Env:GITHUB_WORKSPACE\build\01-armips\SLPM_667.16_VWF.asm"
          Copy-Item -Verbose -Path "$Env:GITHUB_WORKSPACE\build\06-original_files\SLPM_667.16" -Destination "$Env:GITHUB_WORKSPACE\build\01-armips\SLPM_667.16"
          Copy-Item -Verbose -Path "$Env:GITHUB_WORKSPACE\tools\GL5 and 6 abcde scripts\abcde.tbl" -Destination "$Env:GITHUB_WORKSPACE\build\01-armips\abcde.tbl"

          echo "[i] Switch to the armips folder"
          cd "$Env:GITHUB_WORKSPACE\build\01-armips\"
          echo "[i] Patch ELF using armips"
          cmd.exe /C "$Env:GITHUB_WORKSPACE\build\01-armips\armips.exe SLPM_667.16_translation.asm
          cmd.exe /C "$Env:GITHUB_WORKSPACE\build\01-armips\armips.exe SLPM_667.16_VWF.asm

          echo "[i] Move patched ELF"
          Copy-Item -Verbose -Path "$Env:GITHUB_WORKSPACE\build\01-armips\SLPM_667.16" -Destination "$Env:GITHUB_WORKSPACE\build\07-translates_files\SLPM_667.16"

      - name: 05. Patch GL6_FACE.DAT
        shell: powershell
        run: |
          echo "[i] Copy FACE.DAT from the original files folder to the build folder"
          Copy-Item -Verbose -Path "$Env:GITHUB_WORKSPACE\build\06-original_files\GL6_FACE.DAT" -Destination "$Env:GITHUB_WORKSPACE\build\05-build\GL6_FACE.DAT"

          echo "[i] Create the FACE DAT folder and copy all files to it"
          Copy-Item -Recurse -Verbose -Path "$Env:GITHUB_WORKSPACE\build\06-original_files\GL6_FACE DAT*" -Destination "$Env:GITHUB_WORKSPACE\build\05-build\"

          echo "[i] Execute the xdelta patches and save the resulting file in the created folder"
          New-Item -ItemType Directory -Force -Verbose -Path "$Env:GITHUB_WORKSPACE\build\05-build\GL6_FACE DAT\00000144 FACE"
          cmd.exe /C "$Env:GITHUB_WORKSPACE\build\03-xdelta\xdelta-3.1.0-x86_64.exe" -v -d -s "$Env:GITHUB_WORKSPACE\build\06-original_files\GL6_FACE DAT\00000144.FACE_extract\00000000.tm2" "$Env:GITHUB_WORKSPACE\source\GL6_FACE.DAT\00000144.FACE (TIM2 title cards for Warslee, Rio Rey, PMB HQ)\00000000.tm2.vcdiff" "$Env:GITHUB_WORKSPACE\build\05-build\GL6_FACE DAT\00000144 FACE\00000000.tm2"

          New-Item -ItemType Directory -Force -Verbose -Path "$Env:GITHUB_WORKSPACE\build\05-build\GL6_FACE DAT\00000149 FACE"
          cmd.exe /C "$Env:GITHUB_WORKSPACE\build\03-xdelta\xdelta-3.1.0-x86_64.exe" -v -d -s "$Env:GITHUB_WORKSPACE\build\06-original_files\GL6_FACE DAT\00000149.FACE_extract\00000000.tm2" "$Env:GITHUB_WORKSPACE\source\GL6_FACE.DAT\00000149.FACE (TIM2 title cards for Makinus, Dastis, Dragonpit Tower)\00000000.tm2.vcdiff" "$Env:GITHUB_WORKSPACE\build\05-build\GL6_FACE DAT\00000149 FACE\00000000.tm2"

          echo "[i] Start quickBMS XXX.FACE reimport 1 script"
          cmd.exe /C "$Env:GITHUB_WORKSPACE\build\02-quickbms\quickbms.exe" -w -r "$Env:GITHUB_WORKSPACE\tools\GL5 and 6 quickBMS scripts\growlanser.bms" "$Env:GITHUB_WORKSPACE\build\05-build\GL6_FACE DAT\00000144.FACE" "$Env:GITHUB_WORKSPACE\build\05-build\GL6_FACE DAT\00000144 FACE"
          cmd.exe /C "$Env:GITHUB_WORKSPACE\build\02-quickbms\quickbms.exe" -w -r "$Env:GITHUB_WORKSPACE\tools\GL5 and 6 quickBMS scripts\growlanser.bms" "$Env:GITHUB_WORKSPACE\build\05-build\GL6_FACE DAT\00000149.FACE" "$Env:GITHUB_WORKSPACE\build\05-build\GL6_FACE DAT\00000149 FACE"

          echo "[i] Start quickBMS GL6_FACE.DAT reimport 2 script"
          cmd.exe /C "$Env:GITHUB_WORKSPACE\build\02-quickbms\quickbms.exe" -w -r -r "$Env:GITHUB_WORKSPACE\tools\GL5 and 6 quickBMS scripts\growlanser.bms" "$Env:GITHUB_WORKSPACE\build\05-build\GL6_FACE.DAT" "$Env:GITHUB_WORKSPACE\build\05-build\GL6_FACE DAT"

          echo "[i] Move patched FACE.DAT"
          Copy-Item -Verbose -Path "$Env:GITHUB_WORKSPACE\build\05-build\GL6_FACE.DAT" -Destination "$Env:GITHUB_WORKSPACE\build\07-translates_files\GL6_FACE.DAT"

      - name: 07. Patch GL6_FILE.DAT
        shell: powershell
        run: |
          echo "[i] Copy FILE.DAT from the original files folder to the build folder"
          Copy-Item -Verbose -Path "$Env:GITHUB_WORKSPACE\build\06-original_files\GL6_FILE.DAT" -Destination "$Env:GITHUB_WORKSPACE\build\05-build\GL6_FILE.DAT"

          echo "[i] Delete FILE DAT folder and all its contents, create a new folder with the same name"
          New-Item -ItemType Directory -Force -Verbose -Path "$Env:GITHUB_WORKSPACE\build\05-build\GL6_FILE DAT"

          echo "[i] Change to the xdelta folder, execute the xdelta patches and save the resulting file in the build folder"
          cmd.exe /C "$Env:GITHUB_WORKSPACE\build\03-xdelta\xdelta-3.1.0-x86_64.exe" -v -d -s "$Env:GITHUB_WORKSPACE\build\06-original_files\GL6_FILE DAT\00000046.fnt" "$Env:GITHUB_WORKSPACE\source\GL6_FILE.DAT\00000046.fnt Latin Alphabet and Katakana\00000046.fnt.vcdiff" "$Env:GITHUB_WORKSPACE\build\05-build\GL6_FILE DAT\00000046.fnt"
          cmd.exe /C "$Env:GITHUB_WORKSPACE\build\03-xdelta\xdelta-3.1.0-x86_64.exe" -v -d -s "$Env:GITHUB_WORKSPACE\build\06-original_files\GL6_FILE DAT\00000602.tm2" "$Env:GITHUB_WORKSPACE\source\GL6_FILE.DAT\00000602.tm2 GL6 Icons\00000602.tm2.vcdiff" "$Env:GITHUB_WORKSPACE\build\05-build\GL6_FILE DAT\00000602.tm2"
          cmd.exe /C "$Env:GITHUB_WORKSPACE\build\03-xdelta\xdelta-3.1.0-x86_64.exe" -v -d -s "$Env:GITHUB_WORKSPACE\build\06-original_files\GL6_FILE DAT\00000604.tm2" "$Env:GITHUB_WORKSPACE\source\GL6_FILE.DAT\00000604.tm2 Character Menu\00000604.tm2.vcdiff" "$Env:GITHUB_WORKSPACE\build\05-build\GL6_FILE DAT\00000604.tm2"
          cmd.exe /C "$Env:GITHUB_WORKSPACE\build\03-xdelta\xdelta-3.1.0-x86_64.exe" -v -d -s "$Env:GITHUB_WORKSPACE\build\06-original_files\GL6_FILE DAT\00000606.tm2" "$Env:GITHUB_WORKSPACE\source\GL6_FILE.DAT\00000606.tm2 Mission complete screen\00000606.tm2.vcdiff" "$Env:GITHUB_WORKSPACE\build\05-build\GL6_FILE DAT\00000606.tm2"
          cmd.exe /C "$Env:GITHUB_WORKSPACE\build\03-xdelta\xdelta-3.1.0-x86_64.exe" -v -d -s "$Env:GITHUB_WORKSPACE\build\06-original_files\GL6_FILE DAT\00000608.tm2" "$Env:GITHUB_WORKSPACE\source\GL6_FILE.DAT\00000608.tm2 Prologue stats screen\00000608.tm2.vcdiff" "$Env:GITHUB_WORKSPACE\build\05-build\GL6_FILE DAT\00000608.tm2"
          cmd.exe /C "$Env:GITHUB_WORKSPACE\build\03-xdelta\xdelta-3.1.0-x86_64.exe" -v -d -s "$Env:GITHUB_WORKSPACE\build\06-original_files\GL6_FILE DAT\00000611.tm2" "$Env:GITHUB_WORKSPACE\source\GL6_FILE.DAT\00000611.tm2 Yurii Main Menu\00000611.tm2.vcdiff" "$Env:GITHUB_WORKSPACE\build\05-build\GL6_FILE DAT\00000611.tm2"
          cmd.exe /C "$Env:GITHUB_WORKSPACE\build\03-xdelta\xdelta-3.1.0-x86_64.exe" -v -d -s "$Env:GITHUB_WORKSPACE\build\06-original_files\GL6_FILE DAT\00000612.tm2" "$Env:GITHUB_WORKSPACE\source\GL6_FILE.DAT\00000612.tm2 Friend rating screen\00000612.tm2.vcdiff" "$Env:GITHUB_WORKSPACE\build\05-build\GL6_FILE DAT\00000612.tm2"
          cmd.exe /C "$Env:GITHUB_WORKSPACE\build\03-xdelta\xdelta-3.1.0-x86_64.exe" -v -d -s "$Env:GITHUB_WORKSPACE\build\06-original_files\GL6_FILE DAT\00000647.tm2" "$Env:GITHUB_WORKSPACE\source\GL6_FILE.DAT\00000647.tm2 Gem creating screen\00000647.tm2.vcdiff" "$Env:GITHUB_WORKSPACE\build\05-build\GL6_FILE DAT\00000647.tm2"

          echo "[i] Copy and modify the FILE.DAT files that need hexadecimal changes"
          cd "$Env:GITHUB_WORKSPACE\build\05-build\GL6_FILE DAT\"

          Copy-Item -Verbose -Path "$Env:GITHUB_WORKSPACE\source\GL6_FILE.DAT\00000566.mss Spell casting screen text box coord\00000566.asm" -Destination "$Env:GITHUB_WORKSPACE\build\05-build\GL6_FILE DAT\00000566.asm"
          Copy-Item -Verbose -Path "$Env:GITHUB_WORKSPACE\build\06-original_files\GL6_FILE DAT\00000566.mss" -Destination "$Env:GITHUB_WORKSPACE\build\05-build\GL6_FILE DAT\00000566.mss"
          cmd.exe /C "$Env:GITHUB_WORKSPACE\build\01-armips\armips.exe" 00000566.asm
          del "$Env:GITHUB_WORKSPACE\build\05-build\GL6_FILE DAT\00000566.asm"

          Copy-Item -Verbose -Path "$Env:GITHUB_WORKSPACE\source\GL6_FILE.DAT\00000569.mss Yurii Main Menu text box coord\00000569.asm" -Destination "$Env:GITHUB_WORKSPACE\build\05-build\GL6_FILE DAT\00000569.asm"
          Copy-Item -Verbose -Path "$Env:GITHUB_WORKSPACE\build\06-original_files\GL6_FILE DAT\00000569.mss" -Destination "$Env:GITHUB_WORKSPACE\build\05-build\GL6_FILE DAT\00000569.mss"
          cmd.exe /C "$Env:GITHUB_WORKSPACE\build\01-armips\armips.exe" 00000569.asm
          del "$Env:GITHUB_WORKSPACE\build\05-build\GL6_FILE DAT\00000569.asm"

          Copy-Item -Verbose -Path "$Env:GITHUB_WORKSPACE\source\GL6_FILE.DAT\00000570.mss NPC Config Window\00000570.asm" -Destination "$Env:GITHUB_WORKSPACE\build\05-build\GL6_FILE DAT\00000570.asm"
          Copy-Item -Verbose -Path "$Env:GITHUB_WORKSPACE\build\06-original_files\GL6_FILE DAT\00000570.mss" -Destination "$Env:GITHUB_WORKSPACE\build\05-build\GL6_FILE DAT\00000570.mss"
          cmd.exe /C "$Env:GITHUB_WORKSPACE\build\01-armips\armips.exe" 00000570.asm
          del "$Env:GITHUB_WORKSPACE\build\05-build\GL6_FILE DAT\00000570.asm"

          Copy-Item -Verbose -Path "$Env:GITHUB_WORKSPACE\source\GL6_FILE.DAT\00000573.mss Buying and Selling text box coord\00000573.asm" -Destination "$Env:GITHUB_WORKSPACE\build\05-build\GL6_FILE DAT\00000573.asm"
          Copy-Item -Verbose -Path "$Env:GITHUB_WORKSPACE\build\06-original_files\GL6_FILE DAT\00000573.mss" -Destination "$Env:GITHUB_WORKSPACE\build\05-build\GL6_FILE DAT\00000573.mss"
          cmd.exe /C "$Env:GITHUB_WORKSPACE\build\01-armips\armips.exe" 00000573.asm
          del "$Env:GITHUB_WORKSPACE\build\05-build\GL6_FILE DAT\00000573.asm"

          Copy-Item -Verbose -Path "$Env:GITHUB_WORKSPACE\source\GL6_FILE.DAT\00000594.mss Equipment change screen\00000594.asm" -Destination "$Env:GITHUB_WORKSPACE\build\05-build\GL6_FILE DAT\00000594.asm"
          Copy-Item -Verbose -Path "$Env:GITHUB_WORKSPACE\build\06-original_files\GL6_FILE DAT\00000594.mss" -Destination "$Env:GITHUB_WORKSPACE\build\05-build\GL6_FILE DAT\00000594.mss"
          cmd.exe /C "$Env:GITHUB_WORKSPACE\build\01-armips\armips.exe" 00000594.asm
          del "$Env:GITHUB_WORKSPACE\build\05-build\GL6_FILE DAT\00000594.asm"

          Copy-Item -Verbose -Path "$Env:GITHUB_WORKSPACE\source\GL6_FILE.DAT\00000596.mss Winning screen P to KP modification\00000596.asm" -Destination "$Env:GITHUB_WORKSPACE\build\05-build\GL6_FILE DAT\00000596.asm"
          Copy-Item -Verbose -Path "$Env:GITHUB_WORKSPACE\build\06-original_files\GL6_FILE DAT\00000596.mss" -Destination "$Env:GITHUB_WORKSPACE\build\05-build\GL6_FILE DAT\00000596.mss"
          cmd.exe /C "$Env:GITHUB_WORKSPACE\build\01-armips\armips.exe" 00000596.asm
          del "$Env:GITHUB_WORKSPACE\build\05-build\GL6_FILE DAT\00000596.asm"

          Copy-Item -Verbose -Path "$Env:GITHUB_WORKSPACE\source\GL6_FILE.DAT\00000598.mss Teleport screen text box coord\00000598.asm" -Destination "$Env:GITHUB_WORKSPACE\build\05-build\GL6_FILE DAT\00000598.asm"
          Copy-Item -Verbose -Path "$Env:GITHUB_WORKSPACE\build\06-original_files\GL6_FILE DAT\00000598.mss" -Destination "$Env:GITHUB_WORKSPACE\build\05-build\GL6_FILE DAT\00000598.mss"
          cmd.exe /C "$Env:GITHUB_WORKSPACE\build\01-armips\armips.exe" 00000598.asm
          del "$Env:GITHUB_WORKSPACE\build\05-build\GL6_FILE DAT\00000598.asm"

          Copy-Item -Verbose -Path "$Env:GITHUB_WORKSPACE\source\GL6_FILE.DAT\00000803.dat Additional Plate info text\00000803.asm" -Destination "$Env:GITHUB_WORKSPACE\build\05-build\GL6_FILE DAT\00000803.asm"
          Copy-Item -Verbose -Path "$Env:GITHUB_WORKSPACE\build\06-original_files\GL6_FILE DAT\00000803.dat" -Destination "$Env:GITHUB_WORKSPACE\build\05-build\GL6_FILE DAT\00000803.dat"
          cmd.exe /C "$Env:GITHUB_WORKSPACE\build\01-armips\armips.exe" 00000803.asm
          del "$Env:GITHUB_WORKSPACE\build\05-build\GL6_FILE DAT\00000803.asm

          Copy-Item -Verbose -Path "$Env:GITHUB_WORKSPACE\source\GL6_FILE.DAT\00000806.dat Yurii Attributes\00000806.asm" -Destination "$Env:GITHUB_WORKSPACE\build\05-build\GL6_FILE DAT\00000806.asm"
          Copy-Item -Verbose -Path "$Env:GITHUB_WORKSPACE\build\06-original_files\GL6_FILE DAT\00000806.dat" -Destination "$Env:GITHUB_WORKSPACE\build\05-build\GL6_FILE DAT\00000806.dat"
          cmd.exe /C "$Env:GITHUB_WORKSPACE\build\01-armips\armips.exe" 00000806.asm
          del "$Env:GITHUB_WORKSPACE\build\05-build\GL6_FILE DAT\00000806.asm

          echo "[i] Start quickBMS GL6_FILE.DAT reimport 2 script"
          cmd.exe /C "$Env:GITHUB_WORKSPACE\build\02-quickbms\quickbms.exe" -w -r -r "$Env:GITHUB_WORKSPACE\tools\GL5 and 6 quickBMS scripts\growlanser.bms" "$Env:GITHUB_WORKSPACE\build\05-build\GL6_FILE.DAT" "$Env:GITHUB_WORKSPACE\build\05-build\GL6_FILE DAT"

          echo "[i] Move patched FILE.DAT"
          Copy-Item -Verbose -Path "$Env:GITHUB_WORKSPACE\build\05-build\GL6_FILE.DAT" -Destination "$Env:GITHUB_WORKSPACE\build\07-translates_files\GL6_FILE.DAT"

      - name: 06. Translate files
        shell: powershell
        run: |
          echo "[i] cd to the build folder"; cd "$Env:GITHUB_WORKSPACE\build"
          echo "[i] execute build.bat"; cmd.exe -/c ".\build.bat"

      - name: 07. Create patched version
        shell: powershell
        run: |
          echo "[i] Build"
          python "$Env:GITHUB_WORKSPACE\build\04-isotool\isotool.py" --mode insert --iso "$Env:GITHUB_WORKSPACE\build\06-original_files\Growlanser 6 Precarious World.iso" --filelist "$Env:GITHUB_WORKSPACE\build\06-original_files\game_filelist.txt" --files "$Env:GITHUB_WORKSPACE\build\07-translates_files" --output "$Env:GITHUB_WORKSPACE\build\Growlanser 6 Precarious World English.iso" --with-padding

      - name: 08. Create xDelta patch
        shell: powershell
        run: |
          echo "[i] Create xDelta Patch"
          cmd.exe /C "$Env:GITHUB_WORKSPACE\build\03-xdelta\xdelta-3.1.0-x86_64.exe" -e -9 -S djw -vfs "$Env:GITHUB_WORKSPACE\build\06-original_files\Growlanser 6 Precarious World.iso" "$Env:GITHUB_WORKSPACE\build\Growlanser 6 Precarious World English.iso" "$Env:GITHUB_WORKSPACE\build\08-xDeltaPatch\vcdiff\Growlanser 6 Precarious World.iso.vcdiff"

          echo "[i] remove vcdiff\file"
          rm "$Env:GITHUB_WORKSPACE\build\08-xDeltaPatch\vcdiff\file"

      - name: 09. Publish patch
        uses: actions/upload-artifact@v3
        with:
          name: BuildBot-Growlanser_6_English_xDelta_Patch
          path: ${{ github.workspace }}\build\08-xDeltaPatch