name: Build xDelta Patch
on: workflow_dispatch

jobs:
  BuildPatch:
    name: Build xDelta Patch for the Growlanser 6 English Translation
    runs-on: windows-2022
    steps:
      - name: 01. Copy repository
        uses: actions/checkout@v4
        with:
          # Only copy specific folders to the container
          sparse-checkout: |
            .github
            build
            source
            tools

      - name: 02. Prepare files
        shell: powershell
        env:
          TEST: ${{ secrets.TEST }}
          TEST2: ${{ secrets.TEST2 }}
        run: |
          choco install megatools --yes
          # Download files
          megatools get -u "$Env:TEST" -p "$Env:TEST2" --path "$Env:GITHUB_WORKSPACE\build\07-translates_files\DUMMY.DAT" --no-progress /Root/00
          megatools get -u "$Env:TEST" -p "$Env:TEST2" --path "$Env:GITHUB_WORKSPACE\build\07-translates_files\GL6_BTL.DAT" --no-progress /Root/01
          megatools get -u "$Env:TEST" -p "$Env:TEST2" --path "$Env:GITHUB_WORKSPACE\build\07-translates_files\GL6_CHAR.DAT" --no-progress /Root/02
          megatools get -u "$Env:TEST" -p "$Env:TEST2" --path "$Env:GITHUB_WORKSPACE\build\06-original_files\GL6_FACE.DAT" --no-progress /Root/03
          megatools get -u "$Env:TEST" -p "$Env:TEST2" --path "$Env:GITHUB_WORKSPACE\build\06-original_files\GL6_FILE.DAT" --no-progress /Root/04
          megatools get -u "$Env:TEST" -p "$Env:TEST2" --path "$Env:GITHUB_WORKSPACE\build\07-translates_files\GL6_MAP.DAT" --no-progress /Root/05
          megatools get -u "$Env:TEST" -p "$Env:TEST2" --path "$Env:GITHUB_WORKSPACE\build\07-translates_files\GL6_MOV.DAT" --no-progress /Root/06
          megatools get -u "$Env:TEST" -p "$Env:TEST2" --path "$Env:GITHUB_WORKSPACE\build\06-original_files\GL6_SCEN.DAT" --no-progress /Root/07
          megatools get -u "$Env:TEST" -p "$Env:TEST2" --path "$Env:GITHUB_WORKSPACE\build\07-translates_files\GL6_SND.DAT" --no-progress /Root/08
          megatools get -u "$Env:TEST" -p "$Env:TEST2" --path "$Env:GITHUB_WORKSPACE\build\07-translates_files\GL6_VOI.DAT" --no-progress /Root/09
          megatools get -u "$Env:TEST" -p "$Env:TEST2" --path "$Env:GITHUB_WORKSPACE\build\07-translates_files\IOPRP300.IMG" --no-progress /Root/10
          megatools get -u "$Env:TEST" -p "$Env:TEST2" --path "$Env:GITHUB_WORKSPACE\build\06-original_files\SLPM_667.16" --no-progress /Root/11
          megatools get -u "$Env:TEST" -p "$Env:TEST2" --path "$Env:GITHUB_WORKSPACE\build\07-translates_files\SYSTEM.CNF" --no-progress /Root/12
          megatools get -u "$Env:TEST" -p "$Env:TEST2" --path "$Env:GITHUB_WORKSPACE\build\06-original_files\Growlanser 6 Precarious World.iso" --no-progress /Root/13

      - name: 03. Setup the build enviromnent
        shell: pwsh
        run: |
          echo "Create the 05-Build directory"
          mkdir "$Env:GITHUB_WORKSPACE\build\05-build" -Force

          echo "Create the 06-Original files folders for the .DAT files"
          mkdir "$Env:GITHUB_WORKSPACE\build\06-original_files\GL6_FACE DAT" -Force
          mkdir "$Env:GITHUB_WORKSPACE\build\06-original_files\GL6_FILE DAT" -Force
          mkdir "$Env:GITHUB_WORKSPACE\build\06-original_files\GL6_SCEN DAT" -Force

          echo "Copy growlanser.bms, delete later"
          cp "$Env:GITHUB_WORKSPACE\tools\GL5 and 6 quickBMS scripts\growlanser.bms" "$Env:GITHUB_WORKSPACE\build\02-quickbms\growlanser.bms"

          echo "Start quickBMS to dump the .DAT files contents to the original files folder"
          cmd.exe /C "$Env:GITHUB_WORKSPACE\build\02-quickbms\quickbms.exe" -w "$Env:GITHUB_WORKSPACE\tools\GL5 and 6 quickBMS scripts\growlanser.bms" "$Env:GITHUB_WORKSPACE\build\06-original_files\GL6_FACE.DAT" "$Env:GITHUB_WORKSPACE\build\06-original_files\GL6_FACE DAT"
          cmd.exe /C "$Env:GITHUB_WORKSPACE\build\02-quickbms\quickbms.exe" -w "$Env:GITHUB_WORKSPACE\tools\GL5 and 6 quickBMS scripts\growlanser.bms" "$Env:GITHUB_WORKSPACE\build\06-original_files\GL6_FILE.DAT" "$Env:GITHUB_WORKSPACE\build\06-original_files\GL6_FILE DAT"
          cmd.exe /C "$Env:GITHUB_WORKSPACE\build\02-quickbms\quickbms.exe" -w "$Env:GITHUB_WORKSPACE\tools\GL5 and 6 quickBMS scripts\growlanser.bms" "$Env:GITHUB_WORKSPACE\build\06-original_files\GL6_SCEN.DAT" "$Env:GITHUB_WORKSPACE\build\06-original_files\GL6_SCEN DAT"

          echo "Unpack the *.FACE files"
          cmd.exe /C "$Env:GITHUB_WORKSPACE\build\02-quickbms\quickbms.exe" -w -d -F "*.FACE" "$Env:GITHUB_WORKSPACE\tools\GL5 and 6 quickBMS scripts\growlanser.bms" "$Env:GITHUB_WORKSPACE\build\06-original_files\GL6_FACE DAT" "$Env:GITHUB_WORKSPACE\build\06-original_files\GL6_FACE DAT"
      - name: 04. Translate files
        shell: pwsh
        run: |
          echo "cd to the build folder"; cd "$Env:GITHUB_WORKSPACE\build"
          echo "execute build.bat"; cmd.exe -/c ".\build.bat"

      - name: 0x. check filesize
        shell: pwsh
        run: |
          echo "[i] Get GL6_FACE.DAT filesize"
          Get-Childitem -file "$Env:GITHUB_WORKSPACE\build\07-translates_files\GL6_FACE.DAT" | select length

          echo "[i] Get GL6_FILE.DAT filesize"
          Get-Childitem -file "$Env:GITHUB_WORKSPACE\build\07-translates_files\GL6_FILE.DAT" | select length

          echo "[i] Get SCEN.DAT filesize"
          Get-Childitem -file "$Env:GITHUB_WORKSPACE\build\07-translates_files\GL6_SCEN.DAT" | select length

      - name: 05. Create patched version
        shell: pwsh
        run: |
          echo "build"; python "$Env:GITHUB_WORKSPACE\build\04-isotool\isotool.py" --mode insert --iso "$Env:GITHUB_WORKSPACE\build\06-original_files\Growlanser 6 Precarious World.iso" --filelist "$Env:GITHUB_WORKSPACE\build\06-original_files\game_filelist.txt" --files "$Env:GITHUB_WORKSPACE\build\07-translates_files" --output "$Env:GITHUB_WORKSPACE\build\Growlanser 6 Precarious World English.iso" --with-padding
      - name: 06. Create xDelta patch
        shell: pwsh
        run: |
          echo "Create xDelta Patch"
          cmd.exe /C "$Env:GITHUB_WORKSPACE\build\03-xdelta\xdelta-3.1.0-x86_64.exe" -e -9 -S djw -vfs "$Env:GITHUB_WORKSPACE\build\06-original_files\Growlanser 6 Precarious World.iso" "$Env:GITHUB_WORKSPACE\build\Growlanser 6 Precarious World English.iso" "$Env:GITHUB_WORKSPACE\build\08-xDeltaPatch\vcdiff\Growlanser 6 Precarious World.iso.vcdiff"
          
          echo "remove vcdiff\file"
          rm "$Env:GITHUB_WORKSPACE\build\08-xDeltaPatch\vcdiff\file"
      - name: 07. Publish patch
        uses: actions/upload-artifact@v3
        with:
          name: BuildBot-Growlanser_6_English_xDelta_Patch
          path: ${{ github.workspace }}\build\08-xDeltaPatch